updated build spec file

diff --git a/deploy_config/gateway-buildspec.yml b/deploy_config/gateway-buildspec.yml
--- a/deploy_config/gateway-buildspec.yml
+++ b/deploy_config/gateway-buildspec.yml
@@ -50,11 +50,12 @@ phases:
       elif [ "$ENVIRONMENT" = "uat" ]; then
           TASK_DEFINITION_REVISION_NUMBER="1"
       elif [ "$ENVIRONMENT" = "production" ]; then
-          TASK_DEFINITION_REVISION_NUMBER="1"
+          TASK_DEFINITION_REVISION_NUMBER="4"
+          # TASK_DEFINITION_REVISION_NUMBER="7"
       fi
-      # - REPO_NAME="oceanhunter-kong-dashboard"
-      # - ORGANIZATION_NAME="bituslabs"
-      # - CURRENT_TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
+    - REPO_NAME="oceanhunter-kong-dashboard"
+    - ORGANIZATION_NAME="bituslabs"
+    - CURRENT_TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
 
     # Setting endpoint variables
     ## Configured in pipeline variables
@@ -65,6 +66,8 @@ phases:
 
     - DOCKERFILE_PATH="GatewayDockerfile"
     - DOCKERCOMPOSE_FILE_PATH="docker-compose.yml"
+    - SCAN_REPORT_FILE_PATH="deploy_config/generate_scan_report.py"
+    - GITHUB_STATUS_CHECK_FILE_PATH="deploy_config/git_status_check.py"
     - |
       if [ "$ENVIRONMENT" = "dev" ]; then
           CODEDEPLOY_APPSPEC_FILE_PATH="deploy_config/ec2-appspec.yml"
@@ -79,7 +82,7 @@ phases:
     - IMAGE_TAG=${COMMIT_HASH:=latest}
 
     # Adding Status Check (Pending)
-    #   - STATUS=pending python "$GITHUB_STATUS_CHECK_FILE_PATH"
+    - STATUS=pending python "$GITHUB_STATUS_CHECK_FILE_PATH"
 
     # Move appspec file over to root dir
     - mv $CODEDEPLOY_APPSPEC_FILE_PATH ./appspec.yml && CODEDEPLOY_APPSPEC_FILE_PATH="appspec.yml"
@@ -102,10 +105,10 @@ phases:
           sed -i "s|INSERT_ECR_REPO_NAME|$ECR_APP_REPO_URL|g" $CODEDEPLOY_APPLICATION_START_HOOK_FILE_PATH
       else
           # Get Current Task Definition
-          aws ecs describe-task-definition --task-definition $TASK_DEFINITION_ARN:$TASK_DEFINITION_REVISION_NUMBER | jq '.taskDefinition' > taskdef.json
+          aws ecs describe-task-definition --task-definition $GATEWAY_TASK_DEFINITION_ARN:$TASK_DEFINITION_REVISION_NUMBER | jq '.taskDefinition' > taskdef.json
 
           # Replacing appspec placeholders
-          sed -i "s|INSERT_TASK_DEFINITION_ARN|$TASK_DEFINITION_ARN|" $CODEDEPLOY_APPSPEC_FILE_PATH
+          sed -i "s|INSERT_TASK_DEFINITION_ARN|$GATEWAY_TASK_DEFINITION_ARN|" $CODEDEPLOY_APPSPEC_FILE_PATH
           sed -i "s/INSERT_REVISION_NUMBER/$TASK_DEFINITION_REVISION_NUMBER/" $CODEDEPLOY_APPSPEC_FILE_PATH
           sed -i "s/INSERT_CONTAINER_NAME/$SERVICE_NAME/" $CODEDEPLOY_APPSPEC_FILE_PATH
           sed -i "s/INSERT_CONTAINER_PORT/$SERVER_PORT/" $CODEDEPLOY_APPSPEC_FILE_PATH
@@ -113,10 +116,10 @@ phases:
           sed -i "s/INSERT_SECURITY_GROUP/$SECURITY_GROUP/" $CODEDEPLOY_APPSPEC_FILE_PATH
           sed -i "s/INSERT_CAPACITY_PROVIDER_NAME/$CAPACITY_PROVIDER/" $CODEDEPLOY_APPSPEC_FILE_PATH
       fi
-
     # Replacing docker placeholders
     - echo "Getting Ready to Build Docker Image"
-    - sed -i "s|INSERT_BASE_IMAGE|$ECR_BASE_IMAGE_REPO_URL:$ECR_BASE_IMAGE_REPO_TAG|g" $DOCKERFILE_PATH
+    # - sed -i "s|INSERT_BASE_IMAGE|$ECR_BASE_IMAGE_REPO_URL:$ECR_BASE_IMAGE_REPO_TAG|g" $DOCKERFILE_PATH
+    - sed -i "s|INSERT_BASE_IMAGE|$ECR_APP_REPO_URL:latest|g" $DOCKERFILE_PATH
     - sed -i "s|INSERT_ENVIRONMENT|$ENVIRONMENT|g" $DOCKERFILE_PATH
     - sed -i "s|INSERT_RELEASE_DATE|$CURRENT_TIMESTAMP|" $DOCKERFILE_PATH
 
@@ -139,23 +142,23 @@ phases:
     - echo "Starting PostBuild Phase . . ."
 
     # Scanning Image using Trivy
-    - trivy image --scanners vuln,misconfig -f json $ECR_APP_REPO_URL:latest -o scan_report.json
-    - DOCKERFILE_VULNS=$(jq '.Results[] | select(.Type == "dockerfile") | .MisconfSummary.Failures // 0' scan_report.json)
-    - DEPENDENCY_VULNS=$(jq '[.Results[].Vulnerabilities | length] | add // 0' scan_report.json)
-    - |
-      if [ "$DOCKERFILE_VULNS" -gt 0 ] || [ "$DEPENDENCY_VULNS" -gt 0 ]; then
-          echo "Vulnerabilities found. Generating report..."
-          
-          trivy image --scanners vuln,misconfig --quiet $ECR_APP_REPO_URL:latest -o scan_report.txt --table-mode detailed
-          python "$SCAN_REPORT_FILE_PATH"
-          
-          echo "Adding Git Status Check (Failed)"
-          STATUS=failure python "$GITHUB_STATUS_CHECK_FILE_PATH"
+    # - trivy image --scanners vuln,misconfig -f json $ECR_APP_REPO_URL:latest -o scan_report.json
+    # - DOCKERFILE_VULNS=$(jq '.Results[] | select(.Type == "dockerfile") | .MisconfSummary.Failures // 0' scan_report.json)
+    # - DEPENDENCY_VULNS=$(jq '[.Results[].Vulnerabilities | length] | add // 0' scan_report.json)
+    # - |
+    #   if [ "$DOCKERFILE_VULNS" -gt 0 ] || [ "$DEPENDENCY_VULNS" -gt 0 ]; then
+    #       echo "Vulnerabilities found. Generating report..."
 
-          exit 1
-      else
-          echo "No vulnerabilities found, skipping script."
-      fi
+    #       trivy image --scanners vuln,misconfig --quiet $ECR_APP_REPO_URL:latest -o scan_report.txt --table-mode detailed
+    #       python "$SCAN_REPORT_FILE_PATH"
+
+    #       echo "Adding Git Status Check (Failed)"
+    #       STATUS=failure python "$GITHUB_STATUS_CHECK_FILE_PATH"
+
+    #       exit 1
+    #   else
+    #       echo "No vulnerabilities found, skipping script."
+    #   fi
 
     # Adding Git Status Check (Success)
     - STATUS=success python "$GITHUB_STATUS_CHECK_FILE_PATH"
@@ -166,15 +169,16 @@ phases:
     - docker push $ECR_APP_REPO_URL:$IMAGE_TAG
     - docker push $ECR_APP_REPO_URL:latest
 
+    # Setting artifact files
+    - mkdir artifacts
+    - |
+      if [ "$ENVIRONMENT" = "dev" ] || [ "$ENVIRONMENT" = "uat" ]; then
+        mv * artifacts; cp -r artifacts/* .
+      else
+        cp $CODEDEPLOY_APPSPEC_FILE_PATH taskdef.json artifacts/
+      fi
+
 artifacts:
-  base-directory: ${CODEBUILD_SRC_DIR}/
-  name: ec2_build_artifacts
+  base-directory: artifacts/
   files:
   - '**/*'
-  secondary-artifacts:
-    upstream-environments:
-      base-directory: ${CODEBUILD_SRC_DIR}/
-      name: ecs_build_artifacts
-      files:
-      - appspec.yml
-      - taskdef.json
